AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LuckynumgenSingle1x

  Sample SAM Template for LuckynumgenSingle1x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  LuckynumgenSingle1x:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          BUCKET_NAME: "mybucket-jschway939"
          
      CodeUri: function/LuckynumgenSingle1x
      Handler: com.jschway.luckynumgen.HandleOne::handleRequest
      Runtime: java21
      MemorySize: 128
      Architectures:
        - x86_64
      Events:
        LuckynumgenSingle1x:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Method: any
            Path: /onex/{proxy+}
        LuckynumgenBucket:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
              - 's3:ObjectCreated:*'
  LuckynumgenSingle2x:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/LuckynumgenSingle2x
      Handler: com.jschway.luckynumgen.HandleTwo::handleRequest
      Runtime: java21
      MemorySize: 128
      Architectures:
        - x86_64
      Events:
        LuckynumgenSingle1x:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Method: any
            Path: /twox/{proxy+}
  LuckynumgenSingle3x:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/LuckynumgenSingle3x
      Handler: com.jschway.luckynumgen.HandleThree::handleRequest
      Runtime: java21
      MemorySize: 128
      Architectures:
        - x86_64
      Events:
        LuckynumgenSingle1x:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Method: any
            Path: /threex/{proxy+}
  LuckynumgenBucket:
    Type: 'AWS::S3::Bucket'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LuckynumgenSingle1xApi:
    Description: "API Gateway endpoint URL for Prod stage for Lucky Num Gen OneX function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/onex/"
  LuckynumgenSingle2xApi:
    Description: "API Gateway endpoint URL for Prod stage for Lucky Num Gen TwoX function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/twox/"
  LuckynumgenSingle3xApi:
    Description: "API Gateway endpoint URL for Prod stage for Lucky Num Gen ThreeX function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/threex/"
  LuckynumgenSingle1x:
    Description: "Lucky Num Gen OneX Lambda Java ARN"
    Value: !GetAtt LuckynumgenSingle1x.Arn
  LuckynumgenSingle1xIamRole:
    Description: "Implicit IAM Role created for Lucky Num Gen Lambda Java"
    Value: !GetAtt LuckynumgenSingle1x.Arn
